### ISSUE TITLE
Crawling all pages

### ISSUE THREAD

**Issue by alistvt** [pourmand1376/PersianCrawler#1]
Hi dear Amir,
Thanks for sharing your code and dataset,

But there is something I want to ask.
When I looked at your code I saw that you use a `page` variable to iterate through Tasnim pages, however, when I go to the Tasnim website, it seems that it doesn't let us provide `page` greater than 5. In other words, when you provide a page number greater than 5 it will return the same as you entered 5.

Had you noticed this issue and handled it? 
If not the dataset should have duplicate items.

**Comment by pourmand1376** [comment]
Hi, Thanks for your feedback. 

There is no such issue. To show that, check out these urls:
https://www.tasnimnews.com/fa/service/1/?page=1
https://www.tasnimnews.com/fa/service/1/?page=100
https://www.tasnimnews.com/fa/service/1/?page=500

> Note that `?` sign in necessary.

**Comment by alistvt** [comment]
Thanks for your response dear Amir.
Yes I checked that and you are right on this.
The paginator shows only up to 5 pages but indexing with the `page` argument works as expected.
